"""
ConnectScript Compiler
Génère du JavaScript sûr
"""
from ast_nodes import Project, Page, Script, EventHandler, Action, UIElement
from errors import CompileErrorManager, ErrorLevel
from typing import Dict, List, Set
import json


class CodeGenerator:
    """Génère du code JavaScript sûr"""
    
    def __init__(self, project: Project, error_manager: CompileErrorManager):
        self.project = project
        self.error_manager = error_manager
        self.variables: Set[str] = set()
        self.events: Dict[str, List[str]] = {}
    
    def generate(self) -> str:
        """Génère le code JavaScript complet"""
        output = []
        
        # Header
        output.append("// Generated by ConnectScript Compiler")
        output.append("// DO NOT EDIT MANUALLY\n")
        
        # Initialisation de l'app
        output.append("const ConnectApp = {")
        
        # Variables
        output.append("  variables: {},")
        output.append("  pages: {},")
        output.append("  events: {},")
        output.append("  currentPage: null,")
        
        # Initialisation des pages
        output.append("  initPages() {")
        for page_name, page in self.project.pages.items():
            output.append(self._generate_page(page))
        output.append("  },")
        
        # Initialisation des scripts
        output.append("  initScripts() {")
        for script_name, script in self.project.scripts.items():
            output.append(self._generate_script(script))
        output.append("  },")
        
        # Exécution d'action
        output.append(self._generate_execute_action())
        
        # Affichage de page
        output.append(self._generate_show_page())
        
        # Enregistrement d'événement
        output.append(self._generate_register_event())
        
        # Initialisation
        output.append(self._generate_init())
        
        output.append("};")
        
        # Appel d'initialisation
        output.append("\n// Initialize on page load")
        output.append("if (document.readyState === 'loading') {")
        output.append("  document.addEventListener('DOMContentLoaded', () => ConnectApp.init());")
        output.append("} else {")
        output.append("  ConnectApp.init();")
        output.append("}")
        
        return "\n".join(output)
    
    def _generate_page(self, page: Page) -> str:
        """Génère le code pour une page"""
        lines = []
        lines.append(f"  this.pages['{page.name}'] = " + "{")
        lines.append(f"    name: '{page.name}',")
        lines.append(f"    backgroundColor: '{page.background_color}',")
        lines.append("    elements: [")
        
        for element in page.elements:
            lines.append(self._generate_element(element, indent=6))
        
        lines.append("    ]")
        lines.append("  };")
        
        return "\n".join(lines)
    
    def _generate_element(self, element: UIElement, indent: int = 0) -> str:
        """Génère la définition d'un élément"""
        spaces = " " * indent
        props_json = json.dumps(element.properties)
        
        return f"{spaces}" + "{\n" \
            f"{spaces}  type: '{element.element_type}',\n" \
            f"{spaces}  name: '{element.name}',\n" \
            f"{spaces}  properties: {props_json}\n" \
            f"{spaces}" + "},"
    
    def _generate_script(self, script: Script) -> str:
        """Génère le code pour un script"""
        lines = []
        lines.append(f"  this.events['{script.name}'] = " + "{")
        
        for handler in script.event_handlers:
            lines.append(f"    on{handler.event_type.value.capitalize()}: async () => " + "{")
            
            for action in handler.actions:
                lines.append(self._generate_action(action, indent=6))
            
            lines.append("    },")
        
        lines.append("  };")
        
        return "\n".join(lines)
    
    def _generate_action(self, action: Action, indent: int = 4) -> str:
        """Génère le code pour une action"""
        spaces = " " * indent
        action_type = action.action_type
        
        if action_type == "alert":
            message = action.params.get("message", "").replace("'", "\\'")
            return f"{spaces}window.alert('{message}');"
        
        elif action_type == "set":
            var = action.params.get("variable", "")
            val = action.params.get("value", "")
            if isinstance(val, str):
                return f"{spaces}this.variables['{var}'] = '{val}';"
            else:
                return f"{spaces}this.variables['{var}'] = {val};"
        
        elif action_type == "add":
            var = action.params.get("variable", "")
            val = action.params.get("value", 0)
            return f"{spaces}this.variables['{var}'] = (this.variables['{var}'] || 0) + {val};"
        
        elif action_type == "subtract":
            var = action.params.get("variable", "")
            val = action.params.get("value", 0)
            return f"{spaces}this.variables['{var}'] = (this.variables['{var}'] || 0) - {val};"
        
        elif action_type == "goto":
            page = action.params.get("page", "")
            return f"{spaces}await this.showPage('{page}');"
        
        elif action_type == "play":
            sound = action.params.get("sound", "")
            return f"{spaces}// play('{sound}') - not implemented"
        
        elif action_type == "wait":
            seconds = action.params.get("seconds", 1)
            return f"{spaces}await new Promise(r => setTimeout(r, {seconds * 1000}));"
        
        elif action_type == "if":
            condition = action.params.get("condition", "")
            return f"{spaces}if ({condition}) " + "{"
        
        return f"{spaces}// Unknown action: {action_type}"
    
    def _generate_execute_action(self) -> str:
        """Génère la fonction d'exécution d'action"""
        return """  async executeAction(actionName) {
    const parts = actionName.split('.');
    const scriptName = parts[0];
    const script = this.events[scriptName];
    
    if (!script) {
      console.error(`Script not found: ${scriptName}`);
      return;
    }
    
    // Execute the appropriate event handler
    // This is called by UI elements when clicked
    if (script.onClick) {
      await script.onClick();
    }
  },"""
    
    def _generate_show_page(self) -> str:
        """Génère la fonction d'affichage de page"""
        return """  async showPage(pageName) {
    const page = this.pages[pageName];
    if (!page) {
      console.error(`Page not found: ${pageName}`);
      return;
    }
    
    this.currentPage = pageName;
    this.renderPage(page);
  },
  
  renderPage(page) {
    const canvas = document.querySelector('.canvas');
    if (!canvas) return;
    
    // Update background color
    canvas.style.backgroundColor = page.backgroundColor;
    
    // Render elements
    // This would be integrated with the Vue preview
    console.log(`Rendering page: ${page.name}`);
  },"""
    
    def _generate_register_event(self) -> str:
        """Génère la fonction d'enregistrement d'événement"""
        return """  registerEvent(elementName, scriptName, eventType = 'click') {
    // Register event handler for UI element
    // Called when element is clicked
    if (this.events[scriptName] && this.events[scriptName].onClick) {
      // Will be called by the UI framework
    }
  },"""
    
    def _generate_init(self) -> str:
        """Génère la fonction d'initialisation"""
        return """  async init() {
    this.initPages();
    this.initScripts();
    
    // Show the first page
    const firstPageName = Object.keys(this.pages)[0];
    if (firstPageName) {
      await this.showPage(firstPageName);
    }
    
    console.log('ConnectApp initialized');
  }"""


def compile_project(project: Project, error_manager: CompileErrorManager) -> str:
    """Compile le projet en JavaScript"""
    generator = CodeGenerator(project, error_manager)
    return generator.generate()
